version: '3.8'

services:
  frontend:
    build:
      context: ./wedding
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose port 80 for HTTP traffic
    networks:
      - app-network

  server_side:
    build:
      context: ./server_side
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose port 8000 for the backend service
    environment:
      - FLASK_ENV=production  # Use production settings for Flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
